title: Spanda Engineering survey (2024)
remote_theme: pmarsceill/just-the-docs
description: >- # this means to ignore newlines until "baseurl:"
  Spanda Engineering survey (2024)
baseurl: "/spanda-survey" # the subpath of your site, e.g.  /blog
url: "https://github.com/ranga-rangarajan/spanda-survey"

search_enabled: true
color_scheme: survey
exclude: ["*.py", "vendor", "survey", "docs", "cache", "data", "venv", "lib", "templates"]

collections:
  section:
    permalink: "/:collection/:path/"
    output: true
  country:
    permalink: "/:collection/:path/"
    output: true

kramdown:
  toc_levels: 2..2

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2024 Spanda.ai, <a href=\"https://github.com/ranga-rangarajan/spanda-survey/blob/main/LICENSE\">BSD 3-Clause License</a>"

aux_links:
  "Source on GitHub":
    - "//github.com/ranga-rangarajan/spanda-survey"

just_the_docs:
  collections:
    section:
      name: Section
      nav_exclude: false
      search_exclude: false
    country:
      name: Country
      nav_exclude: false
      search_exclude: false
